# Generated by Django 5.2.17 on 2026-08-12 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='internships.category')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('internship_type', models.CharField(choices=[('internship', 'Стажировка'), ('part_time', 'Подработка'), ('project', 'Проектная работа')], max_length=20)),
                ('work_format', models.CharField(choices=[('office', 'Офис'), ('remote', 'Удалённо'), ('hybrid', 'Гибрид')], max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('salary_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('duration_months', models.PositiveSmallIntegerField(default=1)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='internships.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='internships.internship')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='pending', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='internships.internship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('internship', 'student')},
            },
        ),
    ]
